library(checkmate)
library(lubridate)
library(hms)
library(mctq)
library(mockr)
library(testthat)

test_check("mctq")

# # For development use only (comment the code after use (Ctrl + Shift + C))
#
# .rs.restartR()
# devtools::install()
# devtools::document()
# devtools:test()
# devtools::check()
# covr::package_coverage()
# covr::codecov(token = "")
# pkgdown::build_site(preview = TRUE)
# pkgdown::build_favicons(overwrite = TRUE)
# codemetar::write_codemeta()
# codemetar::give_opinions()
# urlchecker::url_check()
# goodpractice::gp()
# spelling::spell_check_package()
# spelling::update_wordlist()
# normalizePath(readClipboard(), "/", mustWork = FALSE)
# usethis::use_logo("./.archive/ai/hex-logo.png")
