library(checkmate)
library(mctq)
library(testthat)

test_check("mctq")

# # For development use only (comment the code after use (Ctrl + Shift + C)).
#
# .rs.restartR()
# codemetar::give_opinions()
# codemetar::write_codemeta()
# covr::package_coverage()
# devtools::check()
# devtools::document()
# devtools::install()
# devtools:test()
# goodpractice::gp()
# normalizePath(readClipboard(), "/", mustWork = FALSE)
# template <- list(package = "rotemplate")
# pkgdown::build_article("mctq", override = list(template = template))
# pkgdown::build_favicons(overwrite = TRUE)
# pkgdown::build_reference(override = list(template = template))
# pkgdown::build_site(devel = FALSE, override = list(template = template))
# rhub::check_for_cran()
# spelling::spell_check_package()
# spelling::update_wordlist()
# urlchecker::url_check()
# usethis::use_coverage()
# usethis::use_github_action("check-pak")
# usethis::use_github_action("test-coverage-pak")
# usethis::use_logo("./.archive/ai/hex-logo.png")
# usethis::use_tidy_description()
